name: Polypheny-UI CI

on: [ pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [ 17, 21 ]
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    name: Java ${{ matrix.java }} @ ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: ./gradlew build